### ISSUE TITLE
Sticky sidebar is no longer working with sticky footer

### ISSUE THREAD

**Issue by jasonadkison** [jasonadkison/formsling#2]
This css:
```scss
// app/javascript/stylesheets/_layout.scss
body > .app-container {
  min-height: 100vh;
  overflow: hidden;
  display: block;
  position: relative;
  padding-bottom: 168px;
  footer.footer {
    height: 168px;
    position: absolute;
    bottom: 0;
    width: 100%
  }
}
```
Breaks the sticky sidebar:

```jsx
// app/javascript/components/FormEditor/Sidebar.js
const Sidebar = () => {
  const { enabled } = useEditor((state) => ({
    enabled: state.options.enabled,
  }));

  if (!enabled) return null;

  return (
    <div className="column is-one-quarter">
      <StickyBox>
        <div className="sidebar">
          <Properties />
        </div>
      </StickyBox>
    </div>
  );
};
```

react-sticky-box demos: [https://react-sticky-box.codecks.io/](https://react-sticky-box.codecks.io/)
